# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build Container

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.10.0 
      - name: Log in to the Container registry
        uses: docker/login-action@v2.2.0
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Setup Pack
        run: |
          sudo add-apt-repository ppa:cncf-buildpacks/pack-cli && \
          sudo apt-get update && \
          sudo apt-get install pack-cli
      - run: |
          pack build ghcr.io/kingsukhoi/random-exporter -B paketobuildpacks/builder-jammy-tiny --env BP_GO_TARGETS="cmd/web"
    
